### ISSUE TITLE
marquee text jumping

### ISSUE THREAD

**Issue by Nerdox** [Lumm1t/obnoxious.club#2]
Hello,
I noticed that marquee text is "jumping" so I decided to fix a issue and I was successful..

### _fixes:_
**index.html**
`<div class="marquee-container" style="display: none">`
replace it with
`<div class="marquee-container" style="visibility: hidden;">`

and also in **portfolio.js**
`$('.marquee-container').fadeIn(100);`
replace it with
`$('.marquee-container').css('visibility','visible').hide().fadeIn(100);`

**my thought why it is happening**
I think plugin cant properly calculate the width of marquee when it is ignored by html, so we have to replace it with visibility

Best regards.

**Comment by alexszolowicz-blockether** [comment]
Fixed, thanks.
