### ISSUE TITLE
The intro doesnt work when the user is using an adblocker

### ISSUE THREAD

**Issue by yTax** [Lumm1t/obnoxious.club#4]
I was doing some testing and apparently the intro doesnt work at all when you use an adblocker, the browser im using is firefox and the adblock im using is uBlock Origin paired with nanodefender to allow me to block ads on website that would give you a popup saying that you have to disable your adblocker.

I did some testing including disabling all extensions and even installing another adblock because ublock origin might be not working correctly and the only way the intro properly loaded was when i uninstalled or disabled the adblocker.

**Comment by alexszolowicz-blockether** [comment]
Adblock is blocking ip trackers, I can't do anything with this.
Thanks for posting.
